"""
signals.py — Detection signal functions for Provenance Guard.

Signal 1: LLM semantic analysis (Groq llama-3.3-70b-versatile)
Signal 2: Stylometric heuristics (pure Python) — added in Milestone 4

Each signal returns a float between 0.0 (very likely human) and 1.0 (very likely AI).
"""

import os
import re
import json
import logging

from dotenv import load_dotenv
from groq import Groq

load_dotenv()
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

_client = None


def _get_groq_client() -> Groq:
    """Initialize and return a Groq client using GROQ_API_KEY from .env."""
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise ValueError(
                "GROQ_API_KEY not set. Add it to a .env file in the project root."
            )
        _client = Groq(api_key=api_key)
    return _client


# ---------------------------------------------------------------------------
# Signal 1: LLM semantic analysis
# ---------------------------------------------------------------------------

def get_llm_score(text: str) -> dict:
    """
    Ask the LLM to assess whether text is human-written or AI-generated.

    Args:
        text (str): The content to analyze.

    Returns:
        dict: {
            "score": float (0.0 = clearly human, 1.0 = clearly AI),
            "reasoning": str (one sentence explanation),
        }
        On failure, returns {"score": 0.5, "reasoning": "LLM analysis unavailable..."}
        — never raises an exception. A failed signal defaults to maximum
        uncertainty (0.5) rather than biasing toward either verdict.
    """
    if not text or not text.strip():
        return {"score": 0.5, "reasoning": "Empty text provided — no analysis possible."}

    prompt = f"""Analyze the following text and determine whether it was written by a human or generated by AI.

Return ONLY a JSON object with exactly these keys:
- "score": a float from 0.0 (clearly human) to 1.0 (clearly AI-generated)
- "reasoning": one sentence explaining the most important signal you observed

Text to analyze:
{text}

JSON only, no explanation outside the JSON, no markdown fences:"""

    try:
        client = _get_groq_client()
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2,
            max_tokens=200,
        )
        raw = response.choices[0].message.content.strip()
        # Strip markdown code fences if the model adds them anyway
        clean = re.sub(r"```(?:json)?", "", raw).strip().rstrip("`").strip()
        parsed = json.loads(clean)

        score = float(parsed.get("score", 0.5))
        score = max(0.0, min(1.0, score))  # clamp to [0, 1]
        reasoning = str(parsed.get("reasoning", "No reasoning provided."))

        return {"score": score, "reasoning": reasoning}

    except json.JSONDecodeError as e:
        logger.error(f"get_llm_score: failed to parse JSON — {e}")
        return {"score": 0.5, "reasoning": "LLM analysis unavailable — response could not be parsed."}
    except Exception as e:
        logger.error(f"get_llm_score: API call failed — {e}")
        return {"score": 0.5, "reasoning": "LLM analysis unavailable — service error."}


# ---------------------------------------------------------------------------
# Signal 2: Stylometric heuristics (pure Python, no external libraries)
# ---------------------------------------------------------------------------

def _split_sentences(text: str) -> list[str]:
    """Naive sentence splitter — splits on . ! ? followed by whitespace/end."""
    sentences = re.split(r"(?<=[.!?])\s+", text.strip())
    return [s.strip() for s in sentences if s.strip()]


def _split_words(text: str) -> list[str]:
    """Naive word splitter — alphabetic tokens, lowercased."""
    return re.findall(r"[A-Za-z']+", text.lower())


def _coefficient_of_variation(values: list[float]) -> float:
    """Standard deviation / mean. Returns 0.0 if mean is 0 or list has <2 items."""
    if len(values) < 2:
        return 0.0
    mean = sum(values) / len(values)
    if mean == 0:
        return 0.0
    variance = sum((v - mean) ** 2 for v in values) / len(values)
    std_dev = variance ** 0.5
    return std_dev / mean


def get_stylometric_score(text: str) -> dict:
    """
    Compute structural/statistical properties that differ between human and
    AI writing, using pure Python with no external libraries.

    Metrics:
      1. Sentence length variance (coefficient of variation of words/sentence)
         — low variance = more AI-like (uniform sentence lengths)
      2. Type-token ratio (unique words / total words)
         — low TTR = more AI-like (narrower vocabulary reuse)
      3. Punctuation density (commas, semicolons, em-dashes per 100 words)
         — distance from a natural range = more AI-like
      4. Word length variance (coefficient of variation of word lengths)
         — low variance = more AI-like (consistent word length choices)

    Args:
        text (str): The content to analyze.

    Returns:
        dict: {
            "score": float (0.0 = clearly human, 1.0 = clearly AI-generated),
            "details": {...}
        }
        Never raises an exception — returns a neutral 0.5 score on degenerate input.
    """
    if not text or not text.strip():
        return {"score": 0.5, "details": {"note": "empty text — no analysis possible"}}

    sentences = _split_sentences(text)
    words = _split_words(text)

    if len(words) < 5 or len(sentences) < 1:
        return {
            "score": 0.5,
            "details": {
                "note": "text too short for reliable stylometric analysis",
                "word_count": len(words),
                "sentence_count": len(sentences),
            },
        }

    # --- Metric 1: sentence length variance ---
    # AI text: CV typically 0.15-0.35 (uniform). Human text: CV typically 0.35-0.70+ (varied).
    sentence_word_counts = [c for c in (len(_split_words(s)) for s in sentences) if c > 0]
    sentence_length_cv = _coefficient_of_variation(sentence_word_counts)
    sentence_variance_score = max(0.0, min(1.0, 1.0 - ((sentence_length_cv - 0.15) / 0.45)))

    # --- Metric 2: type-token ratio ---
    # TTR depends heavily on text length, so we normalize against a length-adjusted
    # expectation rather than a fixed range. For texts in the 50-300 word range,
    # AI text TTR tends to run 0.55-0.70; human text (informal, repetitive "like",
    # "so", filler words) tends to run 0.45-0.65. The signal is weak in isolation
    # for short samples, which is why it's averaged with 3 other metrics.
    unique_words = set(words)
    ttr = len(unique_words) / len(words)
    ttr_score = max(0.0, min(1.0, (ttr - 0.45) / 0.30))

    # --- Metric 3: punctuation density ---
    # AI text: tends toward moderate, consistent comma usage (5-9 per 100 words).
    # Human casual text: often very low (0-3) or irregular/high with dashes, ellipses.
    comma_semicolon_dash = len(re.findall(r"[,;—]", text))
    punctuation_density = (comma_semicolon_dash / len(words)) * 100 if words else 0
    if 5 <= punctuation_density <= 9:
        punctuation_score = 0.75  # squarely in the "consistent AI comma usage" zone
    else:
        distance = min(abs(punctuation_density - 7), 14) / 14
        punctuation_score = 0.75 - (distance * 0.65)
    punctuation_score = max(0.0, min(1.0, punctuation_score))

    # --- Metric 4: word length variance ---
    # AI text: CV typically 0.40-0.50 (consistent word choice). Human text: CV
    # typically 0.45-0.65+ (mix of short filler words and longer ones).
    word_lengths = [len(w) for w in words]
    word_length_cv = _coefficient_of_variation(word_lengths)
    word_length_score = max(0.0, min(1.0, 1.0 - ((word_length_cv - 0.35) / 0.35)))

    combined = (sentence_variance_score + ttr_score + punctuation_score + word_length_score) / 4.0
    combined = max(0.0, min(1.0, combined))

    return {
        "score": round(combined, 4),
        "details": {
            "sentence_count": len(sentences),
            "word_count": len(words),
            "sentence_length_cv": round(sentence_length_cv, 4),
            "type_token_ratio": round(ttr, 4),
            "punctuation_density": round(punctuation_density, 4),
            "word_length_cv": round(word_length_cv, 4),
            "sub_scores": {
                "sentence_variance_score": round(sentence_variance_score, 4),
                "ttr_score": round(ttr_score, 4),
                "punctuation_score": round(punctuation_score, 4),
                "word_length_score": round(word_length_score, 4),
            },
        },
    }


# ---------------------------------------------------------------------------
# Combine signals into a single confidence score
# ---------------------------------------------------------------------------

LLM_WEIGHT = 0.65
STYLOMETRIC_WEIGHT = 0.35

THRESHOLD_HUMAN = 0.31
THRESHOLD_AI = 0.80
SHORT_TEXT_WORD_LIMIT = 100
SHORT_TEXT_CONFIDENCE_CAP = 0.70


def combine_scores(llm_score: float, stylometric_score: float, word_count: int) -> dict:
    """
    Combine the two signals into a single confidence score and determine
    the attribution category, following planning.md Section 2.

    Returns:
        dict: {
            "confidence": float,
            "attribution": str,        # "likely_human" | "uncertain" | "likely_ai"
            "confidence_label": str,   # "high" | "medium" | "low"
            "short_text_warning": bool,
        }
    """
    raw_combined = (llm_score * LLM_WEIGHT) + (stylometric_score * STYLOMETRIC_WEIGHT)
    raw_combined = max(0.0, min(1.0, raw_combined))

    short_text_warning = word_count < SHORT_TEXT_WORD_LIMIT
    confidence = min(raw_combined, SHORT_TEXT_CONFIDENCE_CAP) if short_text_warning else raw_combined

    if confidence < THRESHOLD_HUMAN:
        attribution = "likely_human"
    elif confidence < THRESHOLD_AI:
        attribution = "uncertain"
    else:
        attribution = "likely_ai"

    if short_text_warning and attribution == "likely_ai":
        attribution = "uncertain"

    if confidence < 0.20 or confidence > 0.80:
        confidence_label = "high"
    elif confidence < 0.30 or confidence > 0.65:
        confidence_label = "medium"
    else:
        confidence_label = "low"

    return {
        "confidence": round(confidence, 4),
        "attribution": attribution,
        "confidence_label": confidence_label,
        "short_text_warning": short_text_warning,
    }


# ---------------------------------------------------------------------------
# Quick manual test (run with: python signals.py)
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    test_cases = [
        (
            "Clearly AI-generated",
            "Artificial intelligence represents a transformative paradigm shift in "
            "modern society. It is important to note that while the benefits of AI "
            "are numerous, it is equally essential to consider the ethical implications. "
            "Furthermore, stakeholders across various sectors must collaborate to "
            "ensure responsible deployment.",
        ),
        (
            "Clearly human-written",
            "ok so i finally tried that new ramen place downtown and honestly? "
            "underwhelming. the broth was fine but they put WAY too much sodium in it "
            "and i was thirsty for like three hours after. my friend got the spicy "
            "version and said it was better. probably won't go back unless someone "
            "drags me there",
        ),
        (
            "Borderline: formal human writing",
            "The relationship between monetary policy and asset price inflation has been "
            "extensively studied in the literature. Central banks face a fundamental tension "
            "between their mandate for price stability and the unintended consequences of "
            "prolonged low interest rates on equity and real estate valuations.",
        ),
        (
            "Borderline: lightly edited AI output",
            "I've been thinking a lot about remote work lately. There are genuine tradeoffs — "
            "flexibility and no commute on one side, isolation and blurred work-life boundaries "
            "on the other. Studies show productivity varies widely by individual and role type.",
        ),
    ]

    print("=" * 70)
    print("SIGNAL 1 (LLM) + SIGNAL 2 (Stylometric) + COMBINED SCORE")
    print("=" * 70)

    for label, text in test_cases:
        llm_result = get_llm_score(text)
        style_result = get_stylometric_score(text)
        word_count = len(_split_words(text))
        combined = combine_scores(llm_result["score"], style_result["score"], word_count)

        print(f"\n--- {label} ---")
        print(f"  LLM score:          {llm_result['score']}  ({llm_result['reasoning']})")
        print(f"  Stylometric score:  {style_result['score']}")
        print(f"  Combined confidence: {combined['confidence']}")
        print(f"  Attribution:        {combined['attribution']}")
        print(f"  Confidence label:   {combined['confidence_label']}")
        print(f"  Short text warning: {combined['short_text_warning']}")